using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.SceneManagement;

public class WarehouseSceneManager : MonoBehaviour
{
    public int mazeSize = 11;
    public int numPeople = 2;
    public int numObjects = 10;
    public int lightingLevel = 1;

    public bool autoIdentifyHumans = true;


    private MazeGenerator mazeGenerator;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        LoadVariablesFromPlayerPrefs();
        InitiateMazeGenerator();
        UpdateCameraCapture();
    }   

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKeyDown(KeyCode.Q)){
            ResetScene();
        }
    }

    void LoadVariablesFromPlayerPrefs(){
        mazeSize = PlayerPrefs.GetInt("MazeSize");
        lightingLevel = PlayerPrefs.GetInt("Lighting");
        int val = PlayerPrefs.GetInt("DetectHumans");
        if(val == 0){
            autoIdentifyHumans = false;
        }else{
            autoIdentifyHumans = true;
        }
    }

    void InitiateMazeGenerator(){
        MazeGenerator mazeGenerator = FindFirstObjectByType<MazeGenerator>();
        if(mazeGenerator != null){
            mazeGenerator.lightingLevel = lightingLevel;
            mazeGenerator.mazeHeight = mazeSize;
            mazeGenerator.mazeWidth = mazeSize;
            mazeGenerator.pointCount = numPeople;

            Debug.Log(mazeGenerator.pointCount);
            

            // Instantiate(MazeGenerator);

            mazeGenerator.GenerateMaze();
        }
        
        

    }

    void UpdateCameraCapture(){
        WebSocketCameraCapture cameraCapture = FindFirstObjectByType<WebSocketCameraCapture>();
        if(cameraCapture != null){
            Debug.Log("Camera capture: "+ autoIdentifyHumans);
            cameraCapture.autoIdentifyHumans = autoIdentifyHumans;
        }
    }


    void ResetScene(){
        SceneManager.LoadSceneAsync("Warehouse");
    }
}
